#!/usr/bin/env python3
"""
LedgerFlow development license package generator.

This tool is for development/testing only. It accepts the offline activation
request code generated by the customer device and returns a license package
that the Flutter app can paste into License Settings.

Production note:
- Replace the dev signature with real private-key signing.
- Never ship the private key inside the customer app.
- The customer app should verify with the public key only.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from datetime import datetime, timezone
from typing import Any

REQUEST_PREFIX = "LFREQ."


def b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def b64url_decode(data: str) -> bytes:
    padding = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode(data + padding)


def decode_request_code(request_code: str) -> dict[str, Any]:
    request_code = request_code.strip()
    if not request_code.startswith(REQUEST_PREFIX):
        raise ValueError(f"Invalid request code prefix. Expected {REQUEST_PREFIX}")

    encoded = request_code[len(REQUEST_PREFIX) :]
    raw = b64url_decode(encoded)
    payload = json.loads(raw.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Invalid request payload")
    return payload


def build_features(args: argparse.Namespace) -> dict[str, bool]:
    edition = args.edition

    defaults = {
        "trial": {
            "localMode": True,
            "lanMode": False,
            "hostedMode": False,
            "backupRestore": False,
            "demoCompany": True,
            "advancedInventory": False,
            "payroll": False,
        },
        "solo": {
            "localMode": True,
            "lanMode": False,
            "hostedMode": False,
            "backupRestore": True,
            "demoCompany": True,
            "advancedInventory": False,
            "payroll": False,
        },
        "network": {
            "localMode": True,
            "lanMode": True,
            "hostedMode": False,
            "backupRestore": True,
            "demoCompany": True,
            "advancedInventory": True,
            "payroll": False,
        },
        "hosted": {
            "localMode": False,
            "lanMode": False,
            "hostedMode": True,
            "backupRestore": True,
            "demoCompany": True,
            "advancedInventory": True,
            "payroll": True,
        },
    }[edition].copy()

    for feature in args.enable_feature:
        defaults[feature] = True
    for feature in args.disable_feature:
        defaults[feature] = False

    return defaults


def dev_signature(payload_text: str, dev_secret: str) -> str:
    # Development placeholder. This is NOT production-grade public-key signing.
    digest = hashlib.sha256((payload_text + "|" + dev_secret).encode("utf-8")).digest()
    return b64url_encode(digest)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LedgerFlow development license package")
    parser.add_argument("--request-code", required=True, help="LFREQ offline request code from customer device")
    parser.add_argument("--serial", help="Serial/license key to place in the license package")
    parser.add_argument("--customer-name", help="Licensed customer/company name")
    parser.add_argument("--edition", choices=["trial", "solo", "network", "hosted"], default="solo")
    parser.add_argument("--status", choices=["inactive", "trial", "active", "expired", "blocked"], default="active")
    parser.add_argument("--max-users", type=int, default=None)
    parser.add_argument("--max-devices", type=int, default=None)
    parser.add_argument("--offline-grace-days", type=int, default=None)
    parser.add_argument("--expires-at", default=None, help="ISO date/time or empty for lifetime")
    parser.add_argument("--enable-feature", action="append", default=[], choices=["localMode", "lanMode", "hostedMode", "backupRestore", "demoCompany", "advancedInventory", "payroll"])
    parser.add_argument("--disable-feature", action="append", default=[], choices=["localMode", "lanMode", "hostedMode", "backupRestore", "demoCompany", "advancedInventory", "payroll"])
    parser.add_argument("--dev-secret", default="ledgerflow-dev-secret", help="Development signature secret. Do not use in production.")
    args = parser.parse_args()

    request = decode_request_code(args.request_code)
    now = datetime.now(timezone.utc).isoformat()
    features = build_features(args)

    edition_defaults = {
        "trial": (1, 1, 7),
        "solo": (1, 1, 30),
        "network": (5, 3, 14),
        "hosted": (10, 10, 3),
    }
    default_users, default_devices, default_grace = edition_defaults[args.edition]

    payload = {
        "licenseId": f"lic_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        "serial": args.serial or request.get("serial") or f"LF-{args.edition.upper()}-DEV",
        "customerName": args.customer_name or request.get("customerName") or "Customer",
        "edition": args.edition,
        "status": args.status,
        "maxUsers": args.max_users if args.max_users is not None else default_users,
        "maxDevices": args.max_devices if args.max_devices is not None else default_devices,
        "offlineGraceDays": args.offline_grace_days if args.offline_grace_days is not None else default_grace,
        "features": features,
        "issuedAt": now,
        "expiresAt": args.expires_at,
        "deviceId": request.get("deviceFingerprint"),
        "sourceRequest": {
            "createdAt": request.get("createdAt"),
            "installationId": request.get("installationId"),
            "requestedEdition": request.get("requestedEdition"),
        },
    }

    payload_text = json.dumps(payload, separators=(",", ":"), sort_keys=True)
    package = f"{b64url_encode(payload_text.encode('utf-8'))}.{dev_signature(payload_text, args.dev_secret)}"

    print("\n=== LedgerFlow Development License Package ===\n")
    print(package)
    print("\n=== Decoded Payload Preview ===\n")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("\nWARNING: This uses a development signature placeholder. Replace with private-key signing before production.\n")


if __name__ == "__main__":
    main()
