namespace Zayed.Api.Contracts.Hotels;

public sealed record HotelReservationDto(
    Guid Id,
    string ReservationNumber,
    Guid ContractId,
    string ContractNumber,
    Guid HotelId,
    string HotelName,
    Guid? AgentId,
    string? AgentName,
    Guid RoomTypeId,
    string RoomTypeName,
    Guid MealPlanId,
    string MealPlanName,
    string GuestName,
    string? GuestPhone,
    DateOnly CheckIn,
    DateOnly CheckOut,
    int Nights,
    int Rooms,
    int Adults,
    int Children,
    decimal NightlyRate,
    decimal TotalAmount,
    string Status,
    bool IsActive,
    int AvailableRooms);

public sealed record UpsertHotelReservationRequest(
    string ReservationNumber,
    Guid ContractId,
    Guid HotelId,
    Guid? AgentId,
    Guid RoomTypeId,
    Guid MealPlanId,
    string GuestName,
    string? GuestPhone,
    DateOnly CheckIn,
    DateOnly CheckOut,
    int Rooms,
    int Adults,
    int Children,
    decimal? NightlyRate);
